name: claim-analytics-hub
region: nyc
static_sites:
  - name: web-static
    github:
      branch: main
      deploy_on_push: true
      repo: your-github-username/claim-analytics-hub # Replace with your actual GitHub repo
    build_command: npm ci && npm run build
    output_dir: dist
    routes:
      - path: /
    envs:
      - key: NODE_ENV
        value: production