// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import { ExtendedDatabase } from './rpc-types';

const SUPABASE_URL = "https://piyqnldhdxkmuwqajkhz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBpeXFubGRoZHhrbXV3cWFqa2h6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA0MTgxODUsImV4cCI6MjA1NTk5NDE4NX0.K-NJF3CBlBHGQuNFUvYqrJvw0cOXL53Q6UK79rdhjEI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<ExtendedDatabase>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
